//! IR -> generated artifacts: Mermaid/PlantUML diagrams and per-layer test
//! skeletons (pytest, rstest, Gherkin, Playwright, Rego, conftest,
//! import-linter, dependency-cruiser).
//!
//! Every artifact type is one pure function taking `&Workspace`. Rendering is
//! deterministic: regenerating without IR changes yields byte-identical files.

use std::collections::BTreeMap;

use decispec_ir::names;
use decispec_ir::{Flow, FlowStep, Layer, Spec, Workspace};

pub const HEADER_TEXT: &str =
    "GENERATED BY DECISIONSPEC v0.1 — DO NOT EDIT. Edit specs/*.spec instead.";

#[derive(Debug, Clone)]
pub struct CodegenConfig {
    /// `stack.lang` from decispec.toml: "python" (default) or "rust".
    pub lang: String,
    /// `stack.glue_module`: Python glue import path.
    pub glue_module: String,
    /// `stack.rust_glue`: Rust glue path referenced in `// glue:` comments.
    pub rust_glue: String,
    /// `stack.fitness.root_package`: python package the fitness linters are
    /// rooted at. Empty means "not configured", in which case `.importlinter`
    /// omits the setting rather than emitting an empty value that would make
    /// import-linter fail to parse the file.
    pub root_package: String,
    /// `[stack.fitness.packages]` container-id -> importable module path, so a
    /// model container named `api` can be checked as `myapp.api` instead of a
    /// bare `api` that no interpreter can resolve. Containers with no entry
    /// fall back to the container id (see `fitness_module`).
    pub container_packages: BTreeMap<String, String>,
}

impl Default for CodegenConfig {
    fn default() -> Self {
        CodegenConfig {
            lang: "python".to_string(),
            glue_module: "tests.glue".to_string(),
            rust_glue: "tests/glue/rust".to_string(),
            root_package: String::new(),
            container_packages: BTreeMap::new(),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedFile {
    /// Project-relative path with forward slashes, e.g. `docs/diagrams/x.mmd`.
    pub path: String,
    pub content: String,
}

/// The generated-file header in the comment style appropriate for `path`.
pub fn header(path: &str) -> String {
    let ext = path.rsplit('.').next().unwrap_or("");
    let comment = match ext {
        "mmd" => "%%",
        "puml" => "'",
        "ts" | "cjs" | "rs" => "//",
        _ => "#",
    };
    format!("{comment} {HEADER_TEXT}\n")
}

fn file(path: String, body: String) -> GeneratedFile {
    let content = format!("{}{body}", header(&path));
    GeneratedFile { path, content }
}

// ---------------------------------------------------------------------------
// Diagrams
// ---------------------------------------------------------------------------

pub fn mermaid_flow(flow: &Flow) -> String {
    let mut out = String::from("sequenceDiagram\n");
    render_mermaid_steps(&flow.steps, 1, &mut out);
    out
}

fn render_mermaid_steps(steps: &[FlowStep], depth: usize, out: &mut String) {
    let indent = "    ".repeat(depth);
    for step in steps {
        match step {
            FlowStep::Message {
                from,
                to,
                label,
                dashed,
            } => {
                let arrow = if *dashed { "-->>" } else { "->>" };
                out.push_str(&format!("{indent}{from}{arrow}{to}: {label}\n"));
            }
            FlowStep::Alt {
                name,
                then_branch,
                else_branch,
            } => {
                out.push_str(&format!("{indent}alt {name}\n"));
                render_mermaid_steps(then_branch, depth + 1, out);
                out.push_str(&format!("{indent}else\n"));
                render_mermaid_steps(else_branch, depth + 1, out);
                out.push_str(&format!("{indent}end\n"));
            }
        }
    }
}

pub fn plantuml_flow(flow: &Flow) -> String {
    let mut out = String::from("@startuml\n");
    render_plantuml_steps(&flow.steps, 0, &mut out);
    out.push_str("@enduml\n");
    out
}

fn render_plantuml_steps(steps: &[FlowStep], depth: usize, out: &mut String) {
    let indent = "    ".repeat(depth);
    for step in steps {
        match step {
            FlowStep::Message {
                from,
                to,
                label,
                dashed,
            } => {
                let arrow = if *dashed { "-->" } else { "->" };
                out.push_str(&format!("{indent}{from} {arrow} {to} : {label}\n"));
            }
            FlowStep::Alt {
                name,
                then_branch,
                else_branch,
            } => {
                out.push_str(&format!("{indent}alt {name}\n"));
                render_plantuml_steps(then_branch, depth + 1, out);
                out.push_str(&format!("{indent}else\n"));
                render_plantuml_steps(else_branch, depth + 1, out);
                out.push_str(&format!("{indent}end\n"));
            }
        }
    }
}

/// Mermaid flowchart edge labels (`-->|label|`) cannot contain `(` or `)`
/// (a paren anywhere in one label is a diagram-wide syntax error — verified
/// against mermaid.ink) or `|` (terminates the label early). Render the
/// paren entities and a slash for the pipe; the IR keeps the raw strings.
fn mermaid_edge_label(label: &str) -> String {
    label
        .replace('|', "/")
        .replace('(', "&#40;")
        .replace(')', "&#41;")
}

pub fn mermaid_model(ws: &Workspace) -> String {
    let mut out = String::from("flowchart LR\n");
    for m in &ws.models {
        for c in &m.containers {
            out.push_str(&format!("    {}[\"{}\"]\n", c.id, c.label));
        }
    }
    for rel in ws.all_rels() {
        out.push_str(&format!(
            "    {} -->|{}| {}\n",
            rel.from,
            mermaid_edge_label(&rel.label),
            rel.to
        ));
    }
    out
}

pub fn plantuml_model(ws: &Workspace) -> String {
    let mut out = String::from("@startuml\nleft to right direction\n");
    for m in &ws.models {
        for c in &m.containers {
            out.push_str(&format!("[{}] as {}\n", c.label, c.id));
        }
    }
    for rel in ws.all_rels() {
        out.push_str(&format!("{} --> {} : {}\n", rel.from, rel.to, rel.label));
    }
    out.push_str("@enduml\n");
    out
}

// ---------------------------------------------------------------------------
// unit layer: pytest (+ optional rstest skeletons)
// ---------------------------------------------------------------------------

/// Insert the project root into sys.path so the glue package is importable
/// regardless of pytest's conftest/rootdir handling.
const PYTEST_PATH_BOOTSTRAP: &str = "\
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[3]))

";

pub fn pytest_scenario_test(spec: &Spec, scenario_id: &str, cfg: &CodegenConfig) -> GeneratedFile {
    let test_name = names::pytest_scenario_test_name(&spec.id, scenario_id);
    let then = spec
        .scenario(scenario_id)
        .map(|s| s.then.as_str())
        .unwrap_or("");
    let path = format!(
        "tests/generated/unit/{}",
        names::unit_test_file(&spec.id, scenario_id)
    );
    let body = format!(
        "{PYTEST_PATH_BOOTSTRAP}import pytest\n\nimport {glue} as glue\n\n\n\
         @pytest.mark.parametrize(\"layer\", [\"unit\"])\n\
         def {test_name}(layer):\n\
         \x20   \"\"\"Scenario {scenario_id} (spec {spec_id}): {then}\"\"\"\n\
         \x20   glue.{scenario_id}()\n",
        glue = cfg.glue_module,
        spec_id = spec.id,
    );
    file(path, body)
}

pub fn pytest_invariant_test(
    spec: &Spec,
    invariant: &decispec_ir::Invariant,
    cfg: &CodegenConfig,
) -> GeneratedFile {
    let test_name = names::pytest_invariant_test_name(&spec.id, &invariant.id);
    let path = format!(
        "tests/generated/unit/{}",
        names::invariant_test_file(&spec.id, &invariant.id)
    );
    let body = format!(
        "{PYTEST_PATH_BOOTSTRAP}import {glue} as glue\n\n\n\
         def {test_name}():\n\
         \x20   \"\"\"Invariant {inv_id} (spec {spec_id}):\n\n\
         \x20   {expr}\n\
         \x20   \"\"\"\n\
         \x20   glue.invariant_{inv_id}()\n",
        glue = cfg.glue_module,
        spec_id = spec.id,
        inv_id = invariant.id,
        expr = invariant.expr,
    );
    file(path, body)
}

pub fn rust_unit_skeleton(spec: &Spec, cfg: &CodegenConfig) -> GeneratedFile {
    let mut body = format!("// glue: {}\n\n", cfg.rust_glue);
    for scen in &spec.scenarios {
        if spec.layers_for_scenario(&scen.id).contains(&Layer::Unit) {
            body.push_str(&format!(
                "#[test]\nfn scenario_{}_unit() {{\n    todo!(\"implement per {}\")\n}}\n\n",
                names::sanitize(&scen.id),
                spec.id
            ));
        }
    }
    for inv in &spec.invariants {
        if inv.layers.contains(&Layer::Unit) {
            body.push_str(&format!(
                "#[test]\nfn invariant_{}_unit() {{\n    todo!(\"implement per {}\")\n}}\n\n",
                names::sanitize(&inv.id),
                spec.id
            ));
        }
    }
    let path = format!(
        "tests/generated/unit/rust/{}",
        names::rust_unit_file(&spec.id)
    );
    file(path, body)
}

// ---------------------------------------------------------------------------
// contract layer: Gherkin
// ---------------------------------------------------------------------------

pub fn gherkin_feature(ws: &Workspace, spec: &Spec) -> GeneratedFile {
    let decision = ws.decision(&spec.id);
    let feature_name = decision.map(|d| d.title.as_str()).unwrap_or(&spec.id);
    let mut body = format!("Feature: {feature_name}\n");
    for scen in &spec.scenarios {
        if spec
            .layers_for_scenario(&scen.id)
            .contains(&Layer::Contract)
        {
            body.push_str(&format!(
                "\n  Scenario: {id}\n    Given {given}\n    When {when}\n    Then {then}\n",
                id = names::contract_scenario_test_name(&spec.id, &scen.id),
                given = scen.given,
                when = scen.when,
                then = scen.then
            ));
        }
    }
    let path = format!(
        "tests/generated/contract/{}",
        names::contract_feature_file(&spec.id)
    );
    file(path, body)
}

// ---------------------------------------------------------------------------
// e2e layer: Playwright
// ---------------------------------------------------------------------------

pub fn playwright_spec(spec: &Spec, scenario: &decispec_ir::Scenario) -> GeneratedFile {
    let path = format!("tests/generated/e2e/{}", names::e2e_spec_file(&scenario.id));
    let body = format!(
        "import {{ test, expect }} from '@playwright/test';\n\n\
         test('{spec_id} {scen_id}', async ({{ page }}) => {{\n\
         \x20   // TODO per spec: {then}\n\
         }});\n",
        spec_id = spec.id,
        scen_id = scenario.id,
        then = scenario.then,
    );
    file(path, body)
}

// ---------------------------------------------------------------------------
// infra layer: Rego + conftest.toml
// ---------------------------------------------------------------------------

pub fn rego_policy(policy: &decispec_ir::InfraPolicy) -> GeneratedFile {
    let path = format!(
        "tests/generated/infra/{}",
        names::infra_policy_file(&policy.id)
    );
    let body = format!(
        "package decispec.{id}\n\n\
         # Policy \"{id}\": {description}\n\
         # TODO(decispec): implement the policy body. Example (no_hardcoded_secrets):\n\
         # flag any source/config file assigning a secret-looking literal, e.g.\n\
         #   regex.match(`(?i)(password|api_key|secret)\\s*=\\s*\"[^\"]+\"`, file_content)\n\
         deny[msg] {{\n\
         \x20   false\n\
         \x20   msg := \"{id}: <violation detail>\"\n\
         }}\n",
        id = policy.id,
        description = policy.description,
    );
    file(path, body)
}

pub fn conftest_toml() -> GeneratedFile {
    file(
        "tests/generated/infra/conftest.toml".to_string(),
        "[namespace]\n".to_string(),
    )
}

// ---------------------------------------------------------------------------
// fitness layer: import-linter + dependency-cruiser
// ---------------------------------------------------------------------------

/// Resolve the module path a fitness linter should use for `container`.
///
/// Configured containers map to their real importable package; unconfigured
/// ones fall back to the bare container id so codegen keeps producing a usable
/// (if incomplete) file. Returns `(module, is_configured)`.
///
/// Only the *module positions* of the emitted contract use this. Section names
/// and `name =` lines keep the raw container ids, so a contract's identity does
/// not change when someone edits `decispec.toml`.
fn fitness_module<'a>(cfg: &'a CodegenConfig, container: &'a str) -> (&'a str, bool) {
    match cfg.container_packages.get(container) {
        Some(pkg) => (pkg.as_str(), true),
        None => (container, false),
    }
}

pub fn importlinter(ws: &Workspace, cfg: &CodegenConfig) -> GeneratedFile {
    let mut body = String::from("[importlinter]\n");
    if cfg.root_package.is_empty() {
        body.push_str(
            "# TODO(decispec): set [stack.fitness] root_package in decispec.toml,\n\
             # e.g. root_package = mypkg\n",
        );
    } else {
        body.push_str(&format!("root_package = {}\n", cfg.root_package));
    }
    let mut unmapped: Vec<&str> = Vec::new();
    for rel in ws.all_rels() {
        let (from, from_ok) = fitness_module(cfg, &rel.from);
        let (to, to_ok) = fitness_module(cfg, &rel.to);
        if !from_ok {
            unmapped.push(&rel.from);
        }
        if !to_ok {
            unmapped.push(&rel.to);
        }
        body.push_str(&format!(
            "# rel {from} -> {to} : \"{label}\"\n\
             [contract:rel_{from}_{to}_forbidden]\n\
             name = rel {from} -> {to}: {to} must not import {from}\n\
             type = forbidden\n\
             source_modules =\n    {to_mod}\n\
             forbidden_modules =\n    {from_mod}\n\n\
             [contract:rel_{from}_{to}_allowed]\n\
             name = rel {from} -> {to}: {from} may import {to}\n\
             type = layers\n\
             layers =\n    {from_mod}\n    {to_mod}\n\n",
            from = rel.from,
            to = rel.to,
            from_mod = from,
            to_mod = to,
            label = rel.label,
        ));
    }
    unmapped.sort_unstable();
    unmapped.dedup();
    for c in unmapped {
        body.push_str(&format!(
            "# TODO(decispec): container '{c}' has no [stack.fitness.packages] entry; \
             using it verbatim as a module path\n"
        ));
    }
    file("tests/generated/fitness/.importlinter".to_string(), body)
}

/// dependency-cruiser matches **filesystem** paths in a JS/TS tree, where a
/// container id like `api` is a directory. `container_packages` holds python
/// dotted module paths, so applying it here would emit a regex that can never
/// match. It is deliberately config-independent for that reason.
pub fn depcruise(ws: &Workspace, _cfg: &CodegenConfig) -> GeneratedFile {
    let mut rules = String::new();
    for rel in ws.all_rels() {
        let from = &rel.from;
        let to = &rel.to;
        rules.push_str(&format!(
            "    // rel {from} -> {to} : \"{label}\" (forbid {to} -> {from})\n    {{\n      \
             name: 'decispec-{to}-not-{from}',\n      \
             comment: 'decispec rel {from} -> {to}: {to} must not import {from}',\n      \
severity: 'error',\n      \
             from: {{ path: '(^|[/\\\\]){from}([/\\\\]|$)' }},\n      \
             to: {{ path: '(^|[/\\\\]){to}([/\\\\]|$)' }},\n    }},\n",
            from = from,
            to = to,
            label = rel.label,
        ));
    }
    let body = format!(
        "/** @type {{import('dependency-cruiser').IConfiguration}} */\n\
         module.exports = {{\n  options: {{\n    doNotFollow: {{ path: 'node_modules' }},\n  }},\n  forbidden: [\n{rules}  ],\n}};\n"
    );
    file(
        "tests/generated/fitness/dependency-cruiser.cjs".to_string(),
        body,
    )
}

// ---------------------------------------------------------------------------
// Whole-workspace render
// ---------------------------------------------------------------------------

pub fn render_all(ws: &Workspace, cfg: &CodegenConfig) -> Vec<GeneratedFile> {
    let mut out: Vec<GeneratedFile> = Vec::new();

    // Diagrams: one sequence diagram per flow, one component diagram per model.
    for m in &ws.models {
        for flow in &m.flows {
            out.push(file(
                format!("docs/diagrams/{}.mmd", flow.id),
                mermaid_flow(flow),
            ));
            out.push(file(
                format!("docs/diagrams/{}.puml", flow.id),
                plantuml_flow(flow),
            ));
        }
    }
    let has_model = ws
        .models
        .iter()
        .any(|m| !m.containers.is_empty() || !m.rels.is_empty());
    if has_model {
        out.push(file(
            "docs/diagrams/model.mmd".to_string(),
            mermaid_model(ws),
        ));
        out.push(file(
            "docs/diagrams/model.puml".to_string(),
            plantuml_model(ws),
        ));
    }

    for spec in &ws.specs {
        // unit layer
        for scen in &spec.scenarios {
            if spec.layers_for_scenario(&scen.id).contains(&Layer::Unit) {
                out.push(pytest_scenario_test(spec, &scen.id, cfg));
            }
        }
        for inv in &spec.invariants {
            if inv.layers.contains(&Layer::Unit) {
                out.push(pytest_invariant_test(spec, inv, cfg));
            }
        }
        if cfg.lang == "rust"
            && (spec
                .scenarios
                .iter()
                .any(|s| spec.layers_for_scenario(&s.id).contains(&Layer::Unit))
                || spec
                    .invariants
                    .iter()
                    .any(|i| i.layers.contains(&Layer::Unit)))
        {
            out.push(rust_unit_skeleton(spec, cfg));
        }

        // contract layer
        if spec
            .scenarios
            .iter()
            .any(|s| spec.layers_for_scenario(&s.id).contains(&Layer::Contract))
        {
            out.push(gherkin_feature(ws, spec));
        }

        // e2e layer
        for scen in &spec.scenarios {
            if spec.layers_for_scenario(&scen.id).contains(&Layer::E2e) {
                out.push(playwright_spec(spec, scen));
            }
        }

        // infra layer
        for policy in &spec.infra_policies {
            if policy.layers.contains(&Layer::Infra) {
                out.push(rego_policy(policy));
            }
        }
    }
    if ws
        .specs
        .iter()
        .flat_map(|s| s.infra_policies.iter())
        .any(|p| p.layers.contains(&Layer::Infra))
    {
        out.push(conftest_toml());
    }

    // fitness layer
    if ws.all_rels().next().is_some() {
        out.push(importlinter(ws, cfg));
        out.push(depcruise(ws, cfg));
    }

    out
}

/// True when `content`'s first two lines carry the generated-file header for
/// `path`, exactly as written by [`header`].
pub fn has_generated_header(path: &str, content: &str) -> bool {
    let expected = header(path);
    content
        .lines()
        .take(2)
        .any(|line| line.trim_end() == expected.trim_end())
}

/// True for project-relative paths (forward slashes) that live in a tree
/// `decispec gen` manages: files directly under `docs/diagrams/`, or
/// anywhere under `tests/generated/<layer>/` for a known layer. Deliberately
/// conservative: `tests/generated/results/` (run manifests, written by
/// `decispec test`), files directly under `tests/generated/` and everything
/// under `tests/glue/` are never managed.
pub fn is_managed_path(rel: &str) -> bool {
    let parts: Vec<&str> = rel.split('/').collect();
    if let ["docs", "diagrams", file] = parts.as_slice() {
        return !file.is_empty();
    }
    if let ["tests", "generated", layer, rest @ ..] = parts.as_slice() {
        return !rest.is_empty() && Layer::ALL.iter().any(|l| l.dir() == *layer);
    }
    false
}

#[cfg(test)]
mod tests {
    use super::*;
    use decispec_ir::FlowStep;

    // The codegen crate does not depend on the parser in production, so tests
    // build the demo IR directly.
    mod decispec_parse_for_tests {
        use super::*;
        use decispec_ir::*;

        pub fn parse_demo() -> Workspace {
            let mut ws = Workspace::default();
            ws.decisions.push(Decision {
                id: "AUTH-001".to_string(),
                title: "Use OAuth2 client credentials for service-to-service auth".to_string(),
                status: Status::Accepted,
                context: Some("ctx".to_string()),
                consequences: Some("cons".to_string()),
                superseded_by: None,
                src: Src {
                    file: "specs/0001-auth.spec".to_string(),
                    line: 2,
                },
            });
            let flow = Flow {
                id: "svc_auth".to_string(),
                steps: vec![
                    FlowStep::Message {
                        from: "api".to_string(),
                        to: "auth".to_string(),
                        label: "POST /token".to_string(),
                        dashed: false,
                    },
                    FlowStep::Alt {
                        name: "valid".to_string(),
                        then_branch: vec![FlowStep::Message {
                            from: "auth".to_string(),
                            to: "api".to_string(),
                            label: "200 + access token".to_string(),
                            dashed: true,
                        }],
                        else_branch: vec![FlowStep::Message {
                            from: "auth".to_string(),
                            to: "api".to_string(),
                            label: "401 unauthorized".to_string(),
                            dashed: true,
                        }],
                    },
                ],
                src: Src {
                    file: "specs/0001-auth.spec".to_string(),
                    line: 12,
                },
            };
            ws.models.push(Model {
                containers: vec![
                    Container {
                        id: "api".to_string(),
                        label: "Orders API".to_string(),
                    },
                    Container {
                        id: "auth".to_string(),
                        label: "Auth Service".to_string(),
                    },
                ],
                rels: vec![Rel {
                    from: "api".to_string(),
                    to: "auth".to_string(),
                    label: "requests token".to_string(),
                }],
                flows: vec![flow],
                file: "specs/0001-auth.spec".to_string(),
            });
            ws.specs.push(Spec {
                id: "AUTH-001".to_string(),
                requirements: vec![
                    Requirement {
                        id: "AUTH-001-R1".to_string(),
                        style: Some("EARS".to_string()),
                        text: "WHEN a service presents valid client credentials THEN the auth service SHALL return an access token".to_string(),
                        layers: vec![Layer::Unit, Layer::Contract, Layer::E2e],
                        scenarios: vec!["valid_token".to_string()],
                        src: Src {
                            file: "specs/0001-auth.spec".to_string(),
                            line: 20,
                        },
                    },
                    Requirement {
                        id: "AUTH-001-R2".to_string(),
                        style: Some("EARS".to_string()),
                        text: "WHEN credentials are invalid THEN the auth service SHALL reject with 401".to_string(),
                        layers: vec![Layer::Unit],
                        scenarios: vec!["invalid_token".to_string()],
                        src: Src {
                            file: "specs/0001-auth.spec".to_string(),
                            line: 26,
                        },
                    },
                ],
                scenarios: vec![
                    Scenario {
                        id: "valid_token".to_string(),
                        given: "valid client credentials".to_string(),
                        when: "a token request is made".to_string(),
                        then: "the response status is 200 and a token is returned".to_string(),
                        src: Src {
                            file: "specs/0001-auth.spec".to_string(),
                            line: 31,
                        },
                    },
                    Scenario {
                        id: "invalid_token".to_string(),
                        given: "invalid client credentials".to_string(),
                        when: "a token request is made".to_string(),
                        then: "the response status is 401".to_string(),
                        src: Src {
                            file: "specs/0001-auth.spec".to_string(),
                            line: 36,
                        },
                    },
                ],
                invariants: vec![Invariant {
                    id: "token_ttl".to_string(),
                    expr: "access_token.ttl_seconds <= 3600".to_string(),
                    layers: vec![Layer::Unit],
                    src: Src {
                        file: "specs/0001-auth.spec".to_string(),
                        line: 41,
                    },
                }],
                infra_policies: vec![InfraPolicy {
                    id: "no_hardcoded_secrets".to_string(),
                    description: "No secrets committed in source or config".to_string(),
                    layers: vec![Layer::Infra],
                    src: Src {
                        file: "specs/0001-auth.spec".to_string(),
                        line: 45,
                    },
                }],
                src: Src {
                    file: "specs/0001-auth.spec".to_string(),
                    line: 17,
                },
            });
            ws
        }
    }

    fn nested_alt_flow() -> Flow {
        Flow {
            id: "svc_auth".to_string(),
            steps: vec![
                FlowStep::Message {
                    from: "api".to_string(),
                    to: "auth".to_string(),
                    label: "POST /token".to_string(),
                    dashed: false,
                },
                FlowStep::Alt {
                    name: "valid".to_string(),
                    then_branch: vec![FlowStep::Alt {
                        name: "fresh".to_string(),
                        then_branch: vec![FlowStep::Message {
                            from: "auth".to_string(),
                            to: "api".to_string(),
                            label: "200 + token".to_string(),
                            dashed: true,
                        }],
                        else_branch: vec![FlowStep::Message {
                            from: "auth".to_string(),
                            to: "api".to_string(),
                            label: "200 + refreshed".to_string(),
                            dashed: true,
                        }],
                    }],
                    else_branch: vec![FlowStep::Message {
                        from: "auth".to_string(),
                        to: "api".to_string(),
                        label: "401 unauthorized".to_string(),
                        dashed: true,
                    }],
                },
            ],
            src: decispec_ir::Src {
                file: "specs/0001-auth.spec".to_string(),
                line: 12,
            },
        }
    }

    #[test]
    fn mermaid_flow_with_alt_else() {
        let ws = decispec_parse_for_tests::parse_demo();
        let flow = &ws.models[0].flows[0];
        let expected = "sequenceDiagram\n    api->>auth: POST /token\n    alt valid\n        auth-->>api: 200 + access token\n    else\n        auth-->>api: 401 unauthorized\n    end\n";
        assert_eq!(mermaid_flow(flow), expected);

        let generated = render_all(&ws, &CodegenConfig::default());
        let mmd = generated
            .iter()
            .find(|f| f.path == "docs/diagrams/svc_auth.mmd")
            .expect("svc_auth.mmd missing");
        assert!(mmd.content.starts_with("%% GENERATED BY DECISIONSPEC v0.1"));
        assert!(mmd.content.contains(expected));
    }

    #[test]
    fn plantuml_flow_with_alt_else() {
        let ws = decispec_parse_for_tests::parse_demo();
        let flow = &ws.models[0].flows[0];
        let expected = "@startuml\napi -> auth : POST /token\nalt valid\n    auth --> api : 200 + access token\nelse\n    auth --> api : 401 unauthorized\nend\n@enduml\n";
        assert_eq!(plantuml_flow(flow), expected);
    }

    #[test]
    fn mermaid_flow_with_nested_alt() {
        let flow = nested_alt_flow();
        let expected = concat!(
            "sequenceDiagram\n",
            "    api->>auth: POST /token\n",
            "    alt valid\n",
            "        alt fresh\n",
            "            auth-->>api: 200 + token\n",
            "        else\n",
            "            auth-->>api: 200 + refreshed\n",
            "        end\n",
            "    else\n",
            "        auth-->>api: 401 unauthorized\n",
            "    end\n",
        );
        assert_eq!(mermaid_flow(&flow), expected);
    }

    #[test]
    fn plantuml_flow_with_nested_alt() {
        let flow = nested_alt_flow();
        let expected = concat!(
            "@startuml\n",
            "api -> auth : POST /token\n",
            "alt valid\n",
            "    alt fresh\n",
            "        auth --> api : 200 + token\n",
            "    else\n",
            "        auth --> api : 200 + refreshed\n",
            "    end\n",
            "else\n",
            "    auth --> api : 401 unauthorized\n",
            "end\n",
            "@enduml\n",
        );
        assert_eq!(plantuml_flow(&flow), expected);
    }

    #[test]
    fn model_diagrams_include_containers_and_rels() {
        let ws = decispec_parse_for_tests::parse_demo();
        let generated = render_all(&ws, &CodegenConfig::default());
        let mmd = generated
            .iter()
            .find(|f| f.path == "docs/diagrams/model.mmd")
            .expect("model.mmd missing");
        assert!(mmd.content.contains("flowchart LR\n"));
        assert!(mmd.content.contains("api[\"Orders API\"]"));
        assert!(mmd.content.contains("auth[\"Auth Service\"]"));
        assert!(mmd.content.contains("api -->|requests token| auth"));
        let puml = generated
            .iter()
            .find(|f| f.path == "docs/diagrams/model.puml")
            .expect("model.puml missing");
        assert!(puml.content.contains("[Orders API] as api"));
        assert!(puml.content.contains("api --> auth : requests token"));
    }

    // F19: rel labels with parens break Mermaid flowchart parsing (verified
    // against mermaid.ink: raw parens -> HTTP 400, &#40;/&#41; -> 200); a raw
    // `|` would terminate the edge label early. PlantUML is unaffected.
    fn model_with_rel(label: &str) -> decispec_ir::Workspace {
        let mut ws = decispec_ir::Workspace::default();
        ws.models.push(decispec_ir::Model {
            containers: vec![
                decispec_ir::Container {
                    id: "api".to_string(),
                    label: "API".to_string(),
                },
                decispec_ir::Container {
                    id: "db".to_string(),
                    label: "DB".to_string(),
                },
            ],
            rels: vec![decispec_ir::Rel {
                from: "api".to_string(),
                to: "db".to_string(),
                label: label.to_string(),
            }],
            flows: vec![],
            file: "specs/x.spec".to_string(),
        });
        ws
    }

    #[test]
    fn mermaid_edge_labels_escape_parens() {
        let ws = model_with_rel("queries (api, application)");
        let mmd = mermaid_model(&ws);
        assert!(
            mmd.contains("api -->|queries &#40;api, application&#41;| db"),
            "{mmd}"
        );
        assert!(
            !mmd.contains("-->|queries ("),
            "raw parens in the edge label break Mermaid parsing:\n{mmd}"
        );
    }

    #[test]
    fn mermaid_edge_labels_replace_pipe() {
        let ws = model_with_rel("a | b");
        let mmd = mermaid_model(&ws);
        assert!(mmd.contains("-->|a / b| db"), "{mmd}");
    }

    #[test]
    fn plantuml_edge_labels_keep_raw_parens() {
        let ws = model_with_rel("queries (api, application)");
        let puml = plantuml_model(&ws);
        assert!(
            puml.contains("api --> db : queries (api, application)"),
            "{puml}"
        );
    }

    #[test]
    fn pytest_files_embed_spec_and_item_ids() {
        let ws = decispec_parse_for_tests::parse_demo();
        let generated = render_all(&ws, &CodegenConfig::default());
        let test = generated
            .iter()
            .find(|f| f.path == "tests/generated/unit/test_AUTH_001_valid_token.py")
            .expect("scenario pytest file missing");
        assert!(test.content.starts_with("# GENERATED BY DECISIONSPEC v0.1"));
        assert!(
            test.content
                .contains("def test_scenario_AUTH_001_valid_token_unit(layer):")
        );
        assert!(test.content.contains("glue.valid_token()"));
        assert!(test.content.contains("@pytest.mark.parametrize"));

        let inv = generated
            .iter()
            .find(|f| f.path == "tests/generated/unit/test_invariant_AUTH_001_token_ttl.py")
            .expect("invariant pytest file missing");
        assert!(
            inv.content
                .contains("def test_invariant_AUTH_001_token_ttl_unit():")
        );
        assert!(inv.content.contains("access_token.ttl_seconds <= 3600"));
        assert!(inv.content.contains("glue.invariant_token_ttl()"));
    }

    #[test]
    fn rust_skeletons_emitted_only_for_rust_stack() {
        let ws = decispec_parse_for_tests::parse_demo();
        let py = render_all(&ws, &CodegenConfig::default());
        assert!(!py.iter().any(|f| f.path.ends_with(".rs")));

        let cfg = CodegenConfig {
            lang: "rust".to_string(),
            ..CodegenConfig::default()
        };
        let rust = render_all(&ws, &cfg);
        let rs = rust
            .iter()
            .find(|f| f.path == "tests/generated/unit/rust/AUTH-001.rs")
            .expect("rust skeleton missing");
        assert!(rs.content.starts_with("// GENERATED BY DECISIONSPEC v0.1"));
        assert!(rs.content.contains("// glue: tests/glue/rust"));
        assert!(rs.content.contains("fn scenario_valid_token_unit()"));
        assert!(rs.content.contains("todo!(\"implement per AUTH-001\")"));
    }

    #[test]
    fn contract_e2e_infra_fitness_artifacts() {
        let ws = decispec_parse_for_tests::parse_demo();
        let generated = render_all(&ws, &CodegenConfig::default());

        let feature = generated
            .iter()
            .find(|f| f.path == "tests/generated/contract/AUTH-001.feature")
            .expect("feature missing");
        assert!(
            feature
                .content
                .contains("Feature: Use OAuth2 client credentials for service-to-service auth")
        );
        assert!(feature.content.contains("Scenario: AUTH_001_valid_token"));
        assert!(feature.content.contains("Given valid client credentials"));
        assert!(!feature.content.contains("Scenario: invalid_token"));

        let pw = generated
            .iter()
            .find(|f| f.path == "tests/generated/e2e/valid_token.spec.ts")
            .expect("playwright spec missing");
        assert!(
            pw.content
                .contains("test('AUTH-001 valid_token', async ({ page }) => {")
        );

        let rego = generated
            .iter()
            .find(|f| f.path == "tests/generated/infra/no_hardcoded_secrets.rego")
            .expect("rego missing");
        assert!(
            rego.content
                .contains("package decispec.no_hardcoded_secrets")
        );
        assert!(rego.content.contains("deny[msg]"));
        assert!(
            rego.content
                .contains("regex.match(`(?i)(password|api_key|secret)")
        );

        let conftest = generated
            .iter()
            .find(|f| f.path == "tests/generated/infra/conftest.toml")
            .expect("conftest.toml missing");
        assert!(conftest.content.contains("[namespace]"));

        let il = generated
            .iter()
            .find(|f| f.path == "tests/generated/fitness/.importlinter")
            .expect(".importlinter missing");
        assert!(il.content.contains("type = forbidden"));
        assert!(il.content.contains("type = layers"));

        let dc = generated
            .iter()
            .find(|f| f.path == "tests/generated/fitness/dependency-cruiser.cjs")
            .expect("dependency-cruiser.cjs missing");
        assert!(dc.content.contains("forbidden:"));
        assert!(dc.content.contains("decispec-auth-not-api"));
    }

    #[test]
    fn playwright_spec_shape_is_pinned() {
        let ws = decispec_parse_for_tests::parse_demo();
        let spec = ws.spec_for_decision("AUTH-001").expect("spec missing");
        let scenario = spec.scenario("valid_token").expect("scenario missing");
        let f = playwright_spec(spec, scenario);
        assert_eq!(f.path, "tests/generated/e2e/valid_token.spec.ts");
        assert_eq!(
            f.content,
            "// GENERATED BY DECISIONSPEC v0.1 — DO NOT EDIT. Edit specs/*.spec instead.\n\
             import { test, expect } from '@playwright/test';\n\n\
             test('AUTH-001 valid_token', async ({ page }) => {\n\
             \x20   // TODO per spec: the response status is 200 and a token is returned\n\
             });\n"
        );
    }

    #[test]
    fn contract_feature_is_idempotent() {
        let ws = decispec_parse_for_tests::parse_demo();
        let spec = ws.spec_for_decision("AUTH-001").expect("spec missing");
        let first = gherkin_feature(&ws, spec);
        let second = gherkin_feature(&ws, spec);
        assert_eq!(first.content, second.content);
        assert_eq!(first.path, "tests/generated/contract/AUTH-001.feature");
    }

    #[test]
    fn fitness_modules_use_configured_container_packages() {
        let ws = decispec_parse_for_tests::parse_demo();
        let cfg = CodegenConfig {
            lang: "python".to_string(),
            glue_module: "tests.glue".to_string(),
            rust_glue: "tests/glue/rust".to_string(),
            root_package: "myapp".to_string(),
            // demo's only rel is api -> auth
            container_packages: [
                ("api".to_string(), "myapp.api".to_string()),
                ("auth".to_string(), "myapp.auth".to_string()),
            ]
            .into_iter()
            .collect(),
        };
        let il = importlinter(&ws, &cfg);
        // root_package is emitted uncommented so import-linter can run the file.
        assert!(
            il.content.contains("\nroot_package = myapp\n"),
            "root_package must be a live setting, not a comment:\n{}",
            il.content
        );
        // Container ids are mapped to real python module paths.
        assert!(il.content.contains("myapp.api"), "{}", il.content);
        assert!(il.content.contains("myapp.auth"), "{}", il.content);
        // The bare container id must not leak into module positions.
        assert!(!il.content.contains("\n    api\n"), "{}", il.content);
        assert!(!il.content.contains("\n    auth\n"), "{}", il.content);
        // Nothing unmapped, so no TODO should be emitted.
        assert!(
            !il.content.contains("has no [stack.fitness.packages] entry"),
            "all containers were mapped:\n{}",
            il.content
        );
    }

    #[test]
    fn unmapped_containers_fall_back_to_the_container_id() {
        let ws = decispec_parse_for_tests::parse_demo();
        let cfg = CodegenConfig {
            lang: "python".to_string(),
            glue_module: "tests.glue".to_string(),
            rust_glue: "tests/glue/rust".to_string(),
            root_package: String::new(),
            container_packages: Default::default(),
        };
        let il = importlinter(&ws, &cfg);
        // Unconfigured: keep working as before, but flag that a human must act.
        assert!(il.content.contains("\n    api\n"), "{}", il.content);
        assert!(il.content.contains("\n    auth\n"), "{}", il.content);
        assert!(
            il.content
                .contains("container 'auth' has no [stack.fitness.packages] entry"),
            "unmapped containers must leave an actionable note:\n{}",
            il.content
        );
        // With no root_package we must not emit a bogus empty setting.
        assert!(
            !il.content.contains("root_package =\n"),
            "empty root_package would break import-linter:\n{}",
            il.content
        );
    }

    #[test]
    fn depcruise_keeps_container_ids_as_filesystem_paths() {
        // Regression guard: `container_packages` holds python dotted modules,
        // which must never leak into dependency-cruiser's filesystem regexes.
        let ws = decispec_parse_for_tests::parse_demo();
        let configured = CodegenConfig {
            lang: "python".to_string(),
            glue_module: "tests.glue".to_string(),
            rust_glue: "tests/glue/rust".to_string(),
            root_package: "myapp".to_string(),
            container_packages: [("api".to_string(), "myapp.api".to_string())]
                .into_iter()
                .collect(),
        };
        let with_cfg = depcruise(&ws, &configured);
        let unconfigured = depcruise(&ws, &CodegenConfig::default());
        assert_eq!(with_cfg, unconfigured);
        assert!(
            with_cfg.content.contains(r"(^|[/\\])api([/\\]|$)"),
            "{}",
            with_cfg.content
        );
        assert!(
            !with_cfg.content.contains("myapp.api"),
            "{}",
            with_cfg.content
        );
    }

    #[test]
    fn fitness_contract_identity_survives_config_changes() {
        // Section names / `name =` lines must stay keyed on container ids so a
        // contract does not get a new identity when decispec.toml changes.
        let ws = decispec_parse_for_tests::parse_demo();
        let configured = CodegenConfig {
            root_package: "myapp".to_string(),
            container_packages: [("api".to_string(), "myapp.api".to_string())]
                .into_iter()
                .collect(),
            ..CodegenConfig::default()
        };
        let il = importlinter(&ws, &configured);
        assert!(
            il.content.contains("[contract:rel_api_auth_forbidden]"),
            "{}",
            il.content
        );
        assert!(
            il.content
                .contains("name = rel api -> auth: auth must not import api"),
            "{}",
            il.content
        );
        // ...while the module positions do use the resolved package.
        assert!(il.content.contains("\n    myapp.api\n"), "{}", il.content);
    }

    #[test]
    fn regeneration_is_byte_identical() {
        let ws = decispec_parse_for_tests::parse_demo();
        let cfg = CodegenConfig {
            lang: "rust".to_string(),
            glue_module: "tests.glue".to_string(),
            rust_glue: "tests/glue/rust".to_string(),
            ..CodegenConfig::default()
        };
        let first = render_all(&ws, &cfg);
        let second = render_all(&ws, &cfg);
        assert_eq!(first, second);
        assert!(!first.is_empty());
    }

    #[test]
    fn managed_paths_cover_only_gen_output_trees() {
        for p in [
            "docs/diagrams/svc_auth.mmd",
            "docs/diagrams/model.puml",
            "tests/generated/unit/test_AUTH_001_valid_token.py",
            "tests/generated/unit/rust/AUTH-001.rs",
            "tests/generated/contract/AUTH-001.feature",
            "tests/generated/e2e/valid_token.spec.ts",
            "tests/generated/infra/no_hardcoded_secrets.rego",
            "tests/generated/infra/conftest.toml",
            "tests/generated/fitness/.importlinter",
            "tests/generated/fitness/dependency-cruiser.cjs",
        ] {
            assert!(is_managed_path(p), "{p} should be managed");
        }
        for p in [
            "docs/diagrams/nested/x.mmd", // gen writes flat diagram files only
            "docs/README.md",
            "tests/generated/results/manifest.json", // run manifests, not codegen output
            "tests/generated/results/pytest.xml",
            "tests/generated/root_file.py", // not under a known layer dir
            "tests/generated/other/x.py",
            "tests/glue/__init__.py",
            "tests/glue/generated.py",
            "specs/0001-auth.spec",
            "decispec.toml",
        ] {
            assert!(!is_managed_path(p), "{p} should not be managed");
        }
    }

    #[test]
    fn generated_header_detection_matches_first_two_lines() {
        let ws = decispec_parse_for_tests::parse_demo();
        let generated = render_all(&ws, &CodegenConfig::default());
        assert!(!generated.is_empty());
        for f in &generated {
            assert!(
                has_generated_header(&f.path, &f.content),
                "{} should carry its header",
                f.path
            );
            let body_only = f.content.lines().skip(1).collect::<Vec<_>>().join("\n");
            assert!(
                !has_generated_header(&f.path, &body_only),
                "{0} without its first line must not count as generated",
                f.path
            );
        }
        // Hand-written lookalikes must not match, nor a header past line 2.
        assert!(!has_generated_header(
            "tests/generated/unit/x.py",
            "# hand-written\n"
        ));
        let late_header = format!("#!\n\n{}", header("tests/generated/unit/x.py"));
        assert!(!has_generated_header(
            "tests/generated/unit/x.py",
            &late_header
        ));
    }
}
