# Codegen contract — prefix GEN.
# Every scenario delegates to the codegen/cli/ir Rust test that pins it (F29).

decision GEN-001 "Every generated artifact carries the do-not-edit header and regeneration is byte-identical" {
  status: accepted
  context: "README: 'Everything generated carries a GENERATED BY DECISIONSPEC header; regeneration is byte-identical.' The header is also the stale-sweep's deletion key (GEN-002), so its exact first-two-line shape is pinned by test."
  consequences: "+ agents and humans can tell generated from hand-written at a glance, and re-running gen is a no-op diff. - the header text is now a format contract: changing it invalidates every previously generated file's sweep key."
}

spec GEN-001 {
  requirement GEN-001-R1 (EARS) {
    text: "WHEN gen renders an artifact THEN the file SHALL start with the DecisionSpec do-not-edit header and re-rendering the same workspace SHALL be byte-identical"
    layers: [unit]
    scenarios: [generated_header_detection_matches_first_two_lines, regeneration_is_byte_identical]
  }
  scenario generated_header_detection_matches_first_two_lines {
    given: "any generated file"
    when: "the sweep checks whether it may delete the file"
    then: "the header is matched on its first two lines exactly"
    # delegates: decispec-codegen tests::generated_header_detection_matches_first_two_lines
  }
  scenario regeneration_is_byte_identical {
    given: "a rendered workspace"
    when: "render_all runs again on the same IR"
    then: "every artifact's bytes are unchanged"
    # delegates: decispec-codegen tests::regeneration_is_byte_identical
  }
}

decision GEN-002 "The sweep deletes only stale DecisionSpec artifacts and never creates managed directories" {
  status: accepted
  context: "README: gen 'removes stale artifacts whose spec item disappeared' and 'never touches tests/glue/'. F28 dogfood relies on this: edited spec ids must sweep their old files without endangering foreign files. The cli pins the end-to-end sweep and the absent-directory case."
  consequences: "+ deleting a spec item cleans up after itself, including in the dogfooded repo's own tests/generated. - a file that loses its header (hand edit) becomes foreign and is never swept, by design."
}

spec GEN-002 {
  requirement GEN-002-R1 (EARS) {
    text: "WHEN gen sweeps THEN it SHALL delete only files bearing the DecisionSpec header whose item no longer exists, leave foreign files untouched, and never create managed directories"
    layers: [unit]
    scenarios: [gen_removes_stale_artifacts_and_keeps_foreign_files, sweep_does_not_create_managed_dirs_when_absent]
  }
  scenario gen_removes_stale_artifacts_and_keeps_foreign_files {
    given: "an output tree with a stale generated file and a foreign file"
    when: "gen runs after its spec item disappeared"
    then: "the stale file is deleted and the foreign file remains"
    # delegates: decispec (cli) tests::gen_removes_stale_artifacts_and_keeps_foreign_files
  }
  scenario sweep_does_not_create_managed_dirs_when_absent {
    given: "a project where no artifacts were ever generated"
    when: "the sweep runs"
    then: "no managed directory is created just to sweep it"
    # delegates: decispec (cli) tests::sweep_does_not_create_managed_dirs_when_absent
  }
}

decision GEN-003 "Generated test artifacts embed the spec and item ids the gate matches on" {
  status: accepted
  context: "README 'Codegen mapping': pytest files, contract features, Playwright titles, and rust skeletons all carry the spec item id, sanitized through ir::names (ARCH-003), so gate matching is a name comparison. F6/F23 fixed the escaping half of this contract."
  consequences: "+ the gate needs no out-of-band mapping from artifact to spec item. - the ids become public API: renaming a scenario changes generated test names and can break historical JUnit comparisons."
}

spec GEN-003 {
  requirement GEN-003-R1 (EARS) {
    text: "WHEN artifacts are generated for spec items THEN their file names, test names, and titles SHALL embed the spec and item ids as produced by ir::names"
    layers: [unit]
    scenarios: [pytest_files_embed_spec_and_item_ids, contract_feature_is_idempotent, playwright_spec_shape_is_pinned, rust_skeletons_emitted_only_for_rust_stack, contract_e2e_infra_fitness_artifacts, contract_and_e2e_names_survive_norm]
  }
  scenario pytest_files_embed_spec_and_item_ids {
    given: "a scenario on the unit layer"
    when: "its pytest file is generated"
    then: "the spec id and scenario id appear in the test function name"
    # delegates: decispec-codegen tests::pytest_files_embed_spec_and_item_ids
  }
  scenario contract_feature_is_idempotent {
    given: "a contract-layer scenario"
    when: "its feature file is generated twice"
    then: "the bytes are identical and the scenario name embeds the ids"
    # delegates: decispec-codegen tests::contract_feature_is_idempotent
  }
  scenario playwright_spec_shape_is_pinned {
    given: "an e2e-layer scenario"
    when: "its Playwright spec is generated"
    then: "the title embeds the spec and scenario ids in the pinned shape"
    # delegates: decispec-codegen tests::playwright_spec_shape_is_pinned
  }
  scenario rust_skeletons_emitted_only_for_rust_stack {
    given: "a workspace whose decispec.toml sets lang = rust"
    when: "unit artifacts are generated"
    then: "rstest-style skeletons appear under tests/generated/unit/rust and reference the glue path"
    # delegates: decispec-codegen tests::rust_skeletons_emitted_only_for_rust_stack
  }
  scenario contract_e2e_infra_fitness_artifacts {
    given: "scenarios on contract and e2e plus an infra policy"
    when: "artifacts are generated"
    then: "each layer's artifact set matches the documented mapping"
    # delegates: decispec-codegen tests::contract_e2e_infra_fitness_artifacts
  }
  scenario contract_and_e2e_names_survive_norm {
    given: "ids needing normalization"
    when: "contract and e2e names are produced and normalized"
    then: "the round trip preserves the matchable name"
    # delegates: decispec-ir tests::contract_and_e2e_names_survive_norm
  }
}

decision GEN-004 "Mermaid edge labels are plain ASCII; PlantUML keeps raw labels" {
  status: accepted
  context: "F19/F23 (user-reported, verified against mermaid.ink): GitHub's markdown pipeline decodes HTML entities before Mermaid parses, so only plain characters survive; the charset rule is now [A-Za-z0-9 ,./:-] with parens and pipes collapsed. PlantUML never needed the workaround."
  consequences: "+ diagrams render on GitHub without a 400 from Mermaid. - labels lose characters silently (parens become nothing, other punctuation becomes '-'), which can obscure a label's meaning."
}

spec GEN-004 {
  requirement GEN-004-R1 (EARS) {
    text: "WHEN a diagram edge label is rendered THEN Mermaid SHALL receive plain ASCII from the pinned charset and PlantUML SHALL keep the raw label"
    layers: [unit]
    scenarios: [mermaid_edge_labels_are_plain_ascii_only, mermaid_edge_labels_drop_parens, mermaid_edge_labels_replace_pipe, plantuml_edge_labels_keep_raw_parens]
  }
  scenario mermaid_edge_labels_are_plain_ascii_only {
    given: "a rel label with characters outside the allowed set"
    when: "the mermaid model is rendered"
    then: "the label is plain ASCII from the pinned charset"
    # delegates: decispec-codegen tests::mermaid_edge_labels_are_plain_ascii_only
  }
  scenario mermaid_edge_labels_drop_parens {
    given: "a rel label containing parentheses"
    when: "the mermaid model is rendered"
    then: "the parens are dropped, not entity-escaped"
    # delegates: decispec-codegen tests::mermaid_edge_labels_drop_parens
  }
  scenario mermaid_edge_labels_replace_pipe {
    given: "a rel label containing a pipe"
    when: "the mermaid model is rendered"
    then: "the pipe is replaced so the edge syntax stays parseable"
    # delegates: decispec-codegen tests::mermaid_edge_labels_replace_pipe
  }
  scenario plantuml_edge_labels_keep_raw_parens {
    given: "a rel label containing parentheses"
    when: "the PlantUML diagram is rendered"
    then: "the label is emitted raw"
    # delegates: decispec-codegen tests::plantuml_edge_labels_keep_raw_parens
  }
}

decision GEN-005 "Model and flow diagrams render every declared container, rel, and nested alt/else branch" {
  status: accepted
  context: "The Visitor pattern hazard called out in ARCHITECTURE.md — F4 fixed a validator walk that was one level deep while renderers recursed — is exactly why the nested-alt rendering tests exist for both Mermaid and PlantUML."
  consequences: "+ a flow that nests alt/else renders the same structure in both diagram languages. - rendering is verified at string level only; visual layout is the diagram tool's business."
}

spec GEN-005 {
  requirement GEN-005-R1 (EARS) {
    text: "WHEN the model or a flow is rendered THEN every declared container and rel SHALL appear and nested alt/else blocks SHALL be preserved in both Mermaid and PlantUML"
    layers: [unit]
    scenarios: [model_diagrams_include_containers_and_rels, mermaid_flow_with_alt_else, mermaid_flow_with_nested_alt, plantuml_flow_with_alt_else, plantuml_flow_with_nested_alt]
  }
  scenario model_diagrams_include_containers_and_rels {
    given: "a model with containers and rels"
    when: "the model diagram is rendered"
    then: "every container and rel edge appears"
    # delegates: decispec-codegen tests::model_diagrams_include_containers_and_rels
  }
  scenario mermaid_flow_with_alt_else {
    given: "a flow with alt/else branches"
    when: "the mermaid sequence diagram is rendered"
    then: "alt and else frames appear with sync and return arrows mapped"
    # delegates: decispec-codegen tests::mermaid_flow_with_alt_else
  }
  scenario mermaid_flow_with_nested_alt {
    given: "a flow whose alt branch contains another alt"
    when: "the mermaid sequence diagram is rendered"
    then: "the nesting is preserved"
    # delegates: decispec-codegen tests::mermaid_flow_with_nested_alt
  }
  scenario plantuml_flow_with_alt_else {
    given: "a flow with alt/else branches"
    when: "the PlantUML diagram is rendered"
    then: "alt/else groups appear"
    # delegates: decispec-codegen tests::plantuml_flow_with_alt_else
  }
  scenario plantuml_flow_with_nested_alt {
    given: "a flow whose alt branch contains another alt"
    when: "the PlantUML diagram is rendered"
    then: "the nesting is preserved"
    # delegates: decispec-codegen tests::plantuml_flow_with_nested_alt
  }
}

decision GEN-006 "The decision index renders a GitHub-ready page or exits 2 on broken specs" {
  status: accepted
  context: "F20 landed index as an on-demand render (docs/decisions.md) with mermaid fences, escaped table cells, and the superseded_by line; it reuses the gen family's load-or-bail rule so a broken workspace exits 2 instead of publishing a stale page."
  consequences: "+ anyone browsing the repo sees the whole decision picture without running the tool. - the index is generated on demand only, so it rots unless a human or CI runs decispec index after spec edits."
}

spec GEN-006 {
  requirement GEN-006-R1 (EARS) {
    text: "WHEN index runs on a valid workspace THEN it SHALL render mermaid fences and decision tables into docs/decisions.md or the --out path with markdown escaping and exit 2 when specs do not parse"
    layers: [unit]
    scenarios: [index_renders_title_mermaid_fences_and_tables, index_escapes_table_cells, index_renders_superseded_by_line, index_honors_out_override, index_exits_2_when_specs_are_broken]
  }
  scenario index_renders_title_mermaid_fences_and_tables {
    given: "a valid workspace"
    when: "render_index runs"
    then: "the page carries the title, mermaid fences, and decision tables"
    # delegates: decispec-codegen tests::index_renders_title_mermaid_fences_and_tables
  }
  scenario index_escapes_table_cells {
    given: "decision text containing pipes or newlines"
    when: "the index tables are rendered"
    then: "cells are markdown-escaped"
    # delegates: decispec-codegen tests::index_escapes_table_cells
  }
  scenario index_renders_superseded_by_line {
    given: "a superseded decision with a successor"
    when: "the index tables are rendered"
    then: "the superseded_by line names the successor"
    # delegates: decispec-codegen tests::index_renders_superseded_by_line
  }
  scenario index_honors_out_override {
    given: "an --out argument"
    when: "decispec index runs"
    then: "the page is written to the override path"
    # delegates: decispec (cli) tests::index_honors_out_override
  }
  scenario index_exits_2_when_specs_are_broken {
    given: "specs that fail validation"
    when: "decispec index runs"
    then: "it exits 2"
    # delegates: decispec (cli) tests::index_exits_2_when_specs_are_broken
  }
}

decision GEN-007 "Fitness configs are emitted only for fully-mapped rels and never abort the toolchain" {
  status: accepted
  context: "F27 (verified against import-linter 2.5.2): a contract naming an unmapped container aborts the whole file, and sections must be spelled importlinter:contract:<id> or zero contracts evaluate. F9 (verified against dependency-cruiser 18.5.0): rules must forbid the to-side importing the from-side with segment-anchored paths or allowed imports fail and siblings false-positive."
  consequences: "+ the fitness row means something when green: contracts evaluated and paths anchored. - rels with an unmapped endpoint are only TODO comments, so their direction is unenforced until someone maps the container."
}

spec GEN-007 {
  requirement GEN-007-R1 (EARS) {
    text: "WHEN fitness artifacts are generated THEN an import-linter contract SHALL exist only when both containers are mapped, unmapped endpoints SHALL become TODOs, and dependency-cruiser rules SHALL forbid the to-side importing the from-side with segment-anchored paths"
    layers: [unit]
    scenarios: [importlinter_emits_contracts_only_for_python_mapped_rels, unmapped_containers_get_todos_instead_of_bogus_contracts, fitness_modules_use_configured_container_packages, fitness_contract_identity_survives_config_changes, depcruise_forbids_the_to_side_from_importing_the_from_side, depcruise_paths_are_segment_anchored_without_rejected_regex_constructs, depcruise_keeps_container_ids_as_filesystem_paths, depcruise_config_documents_that_paths_match_container_directories]
  }
  scenario importlinter_emits_contracts_only_for_python_mapped_rels {
    given: "rels with zero, one, or two mapped endpoints"
    when: "the .importlinter file is generated"
    then: "contracts exist only for fully mapped rels under importlinter: sections"
    # delegates: decispec-codegen tests::importlinter_emits_contracts_only_for_python_mapped_rels
  }
  scenario unmapped_containers_get_todos_instead_of_bogus_contracts {
    given: "a rel with an unmapped endpoint"
    when: "the .importlinter file is generated"
    then: "a TODO names the container to map and no contract references it"
    # delegates: decispec-codegen tests::unmapped_containers_get_todos_instead_of_bogus_contracts
  }
  scenario fitness_modules_use_configured_container_packages {
    given: "a [stack.fitness.packages] mapping"
    when: "contracts are generated"
    then: "modules use the configured dotted paths"
    # delegates: decispec-codegen tests::fitness_modules_use_configured_container_packages
  }
  scenario fitness_contract_identity_survives_config_changes {
    given: "a rel with mapped endpoints"
    when: "decispec.toml's package mapping is edited"
    then: "the contract section identity stays stable"
    # delegates: decispec-codegen tests::fitness_contract_identity_survives_config_changes
  }
  scenario depcruise_forbids_the_to_side_from_importing_the_from_side {
    given: "a rel a -> b"
    when: "the dependency-cruiser config is generated"
    then: "the forbidden direction is b importing a, asserted by side"
    # delegates: decispec-codegen tests::depcruise_forbids_the_to_side_from_importing_the_from_side
  }
  scenario depcruise_paths_are_segment_anchored_without_rejected_regex_constructs {
    given: "container ids as paths"
    when: "the dependency-cruiser config is generated"
    then: "paths are segment-anchored and free of constructs depcruise rejects as unsafe"
    # delegates: decispec-codegen tests::depcruise_paths_are_segment_anchored_without_rejected_regex_constructs
  }
  scenario depcruise_keeps_container_ids_as_filesystem_paths {
    given: "a JS/TS tree where a container is a directory"
    when: "the dependency-cruiser config is generated"
    then: "container ids stay filesystem path segments"
    # delegates: decispec-codegen tests::depcruise_keeps_container_ids_as_filesystem_paths
  }
  scenario depcruise_config_documents_that_paths_match_container_directories {
    given: "the generated dependency-cruiser config"
    when: "a reader checks the path convention"
    then: "the config documents that paths match container directories"
    # delegates: decispec-codegen tests::depcruise_config_documents_that_paths_match_container_directories
  }
}
